language: node_js
sudo: false

node_js:
  - "node"
  - "6.6.x"

deploy:
  provider: heroku
  app: metalsmith
  api_key:
    secure: NYg/59wPJrES3wcKGeKMPZ5cN9NRBGV47fmJa5YEZWA/tstXHBdn9aryWZD5gG3xjFsbtnuf0n3wo+EkJwG6lg0DCKnKnrWCk8/Y7yfsvErD+O1/pIsjlqhpTW9iPw6G0Qa2NgtfZSTv9qJRGgNJ6xbg7aArsMrYiGEiptfO3dg=
  on:
    node: "6.6.x"